# general settings
entities:
  mob-ai: true
  auto-spawn-tick: 2400
  worlds-spawn-disabled: 
  - world

# max spawn settings
max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 3
  cow: 4
  creeper: 1
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 2
  husk: 0
  iron-golem: 0
  mooshroom: 0
  mule: 0
  ocelot: 0
  pig: 4
  pig-zombie: 0
  rabbit: 2
  silverfish: 0
  sheep: 4
  skeleton: 2
  stray: 0
  skeleton-horse: 0
  snow-golem: 0
  spider: 2
  wolf: 2
  zombie: 2
  zombie-horse: 0
  zombie-villager: 1
 
