# general settings
entities:
  mob-ai: true
  auto-spawn-tick: 800
  worlds-spawn-disabled: 

# max spawn settings
max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 2
  cow: 1
  creeper: 0
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 0
  husk: 0 
  iron-golem: 0
  mooshroom: 0
  mule: 0
  ocelot: 1
  pig: 2
  pig-zombie: 0
  rabbit: 1
  stray: 1
  silverfish: 0
  sheep: 2
  skeleton: 1
  skeleton-horse: 0
  snow-golem: 0
  spider: 0
  wolf: 1
  zombie: 1
  zombie-horse: 0
  zombie-villager: 0
 
