name: MobPlugin
main: com.pikycz.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]
author: kniffo80,PikyCZ,CreeperFace,NycuRO

commands:
  mob:
    description: Spawn a simple mob to the player, that is using this command
    aliases: ["mob"]
    usage: "/mob spawn,removemobs,removeitems"
    permission: mob-plugin.mob
    
permissions:
  mob-plugin.mob:
    description: ""
    default: op
