name: MobPlugin
main: com.pikycz.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]
author: kniffo80,PikyCZ,CreeperFace,NycuRO

commands:
  mob:
    description: Spawn a simple mob to the player, that is using this command
    aliases: ["mob"]
    usage: "/mob spawn <mob_name>"
    permission: mob-plugin.mob
  removemobs:
    description: Remove all living mobs
    aliases: ["removeall"]
    usage: "/mob removeall"
    permission: mob-plugin.removemobs
  removeitems:
    description: Remove all items from all levels (ground)
    aliases: ["removeitems"]
    usage: "/mob removeitems"
    permission: mob-plugin.removeitems
    
permissions:
  mob-plugin.mob:
    description: ""
    default: op
  mob.plugin.removemobs:
    description: ""
    default: op
  mob-plugin.removeitems:
    description: ""
    default: op
