name: MobPlugin
main: com.pikycz.mobplugin.MobPlugin
version: "1.1"
api: ["1.0.0"]

load: STARTUP
author: PikyCZ.CreeperFace.kniffo80
description: Implement Entity AI from scratch beginning with 1.1.x
website: https://github.com/PikyCZ/MobPlugin

commands:
  mob:
    description: Spawn a simple mob to the player, that is using this command
    aliases: ["mob"]
    usage: ""
    permission: mob-plugin.mob  
    
permissions:
  mob-plugin.mob:
    description: ""
    default: op
    
